### ISSUE TITLE
Index out of range" when deleting all digit rectangles in the web app

### ISSUE THREAD

**Issue by jensb** [jomjol/water-meter-config-creator-web-application#1]
Request Method: POST

http://wasserzaehler.ignorelist.com/make_digit/
2.2.5
IndexError
list index out of range
/opt/app/configurator/lib/ConfigCreator.py in UpdateDigit, line 341
/usr/local/bin/python
3.7.6
['/opt/app/config_creator',  '/usr/local/bin',  '/opt/app',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
Fri, 10 Apr 2020 13:20:47 +0000

Traceback Switch to copy-and-paste view
/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) …
▶ Local vars
/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) …
▶ Local vars
/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) …
▶ Local vars
/opt/app/configurator/views/make_digit.py in make_digit
            session_act.UpdateDigit(refact, refx, refy, refdx, refdy) …
▶ Local vars
/opt/app/configurator/lib/ConfigCreator.py in UpdateDigit
        self.cutimage.Digital_Digit[refact][1] = zw …
▶ Local vars

**Comment by jomjol** [comment]
Error corrected - the last digital rectangle cannot be deleted anymore --> no out of range!

@jensb: Thanks for the feedback!
